import QueryError from "@/components/QueryError";
import { formatDateTime, PRIORITY_LABELS } from "@/lib/crm";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Check, CircleAlert, ClipboardList, Plus, Target, Trash2 } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

type ActivityStatus = "pending" | "completed" | "cancelled";
const statusLabel: Record<ActivityStatus, string> = { pending: "Pendentes", completed: "Concluídas", cancelled: "Canceladas" };

export default function Activities() {
  const utils = trpc.useUtils();
  const [status, setStatus] = useState<ActivityStatus>("pending");
  const [dialogOpen, setDialogOpen] = useState(false);
  const [form, setForm] = useState({ type: "task" as "task" | "appointment", title: "", description: "", clientId: "", opportunityId: "", priority: "medium" as "low" | "medium" | "high", dueAt: "" });
  const activities = trpc.activities.list.useQuery({ status });
  const clients = trpc.clients.options.useQuery();
  const opportunities = trpc.opportunities.list.useQuery(useMemo(() => ({ page: 1, pageSize: 100 }), []));
  const create = trpc.activities.create.useMutation();
  const updateStatus = trpc.activities.updateStatus.useMutation();
  const inactivate = trpc.activities.inactivate.useMutation();
  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    create.mutate({ ...form, description: form.description || null, clientId: form.clientId ? Number(form.clientId) : null, opportunityId: form.opportunityId ? Number(form.opportunityId) : null, dueAt: form.dueAt ? new Date(form.dueAt) : null }, {
      onSuccess: () => { toast.success(form.type === "task" ? "Tarefa criada." : "Compromisso criado."); setForm({ type: "task", title: "", description: "", clientId: "", opportunityId: "", priority: "medium", dueAt: "" }); setDialogOpen(false); void utils.activities.list.invalidate(); void utils.dashboard.get.invalidate(); },
      onError: error => toast.error(error.message),
    });
  }
  function changeStatus(id: number, nextStatus: ActivityStatus) { updateStatus.mutate({ id, status: nextStatus }, { onSuccess: () => { toast.success(nextStatus === "completed" ? "Atividade concluída." : "Status atualizado."); void utils.activities.list.invalidate(); void utils.dashboard.get.invalidate(); }, onError: error => toast.error(error.message) }); }
  function inactivateRecord(id: number, title: string) { if (!window.confirm(`Inativar a atividade “${title}”? O histórico continuará preservado.`)) return; inactivate.mutate({ id }, { onSuccess: () => { toast.success("Atividade inativada com histórico preservado."); void utils.activities.list.invalidate(); void utils.dashboard.get.invalidate(); }, onError: error => toast.error(error.message) }); }
  if (activities.isError) return <QueryError message="Não foi possível carregar as atividades comerciais." onRetry={() => void activities.refetch()} />;
  return <div className="space-y-7"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">ROTINA COMERCIAL</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-[#172033]">Atividades e compromissos</h1><p className="mt-2 text-sm text-slate-500">Transforme os próximos passos em ações claras e acompanháveis.</p></div><button onClick={() => setDialogOpen(true)} className="crm-button-primary"><Plus className="h-4 w-4" /> Nova atividade</button></section>
    <section className="flex flex-wrap gap-2">{(Object.keys(statusLabel) as ActivityStatus[]).map(item => <button key={item} onClick={() => setStatus(item)} className={`rounded-lg px-4 py-2 text-xs font-semibold transition ${status === item ? "bg-[#27365b] text-white shadow-md shadow-slate-900/10" : "border border-slate-200 bg-white text-slate-500 hover:bg-slate-50"}`}>{statusLabel[item]}</button>)}</section>
    <section className="crm-card overflow-hidden"><div className="overflow-x-auto"><table className="crm-table"><thead><tr><th>Atividade</th><th>Vínculo</th><th>Prioridade</th><th>Prazo</th><th className="text-right">Ação</th></tr></thead><tbody>{activities.isLoading ? <tr><td colSpan={5} className="py-12 text-center text-sm text-slate-400">Carregando atividades...</td></tr> : (activities.data ?? []).length === 0 ? <tr><td colSpan={5} className="py-14 text-center"><ClipboardList className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3 text-sm font-medium text-slate-500">Nenhuma atividade nesta visão</p><p className="mt-1 text-xs text-slate-400">Crie uma tarefa ou compromisso para manter o ritmo comercial.</p></td></tr> : activities.data?.map(item => <tr key={item.id}><td><div className="flex items-center gap-3"><span className={`flex h-9 w-9 items-center justify-center rounded-xl ${item.type === "task" ? "bg-[#eef0ff] text-[#4c58a8]" : "bg-[#fff5e9] text-[#b87d28]"}`}>{item.type === "task" ? <ClipboardList className="h-4 w-4" /> : <CalendarDays className="h-4 w-4" />}</span><div><p className="font-semibold text-slate-700">{item.title}</p><p className="mt-0.5 text-xs text-slate-400">{item.type === "task" ? "Tarefa" : "Compromisso"}{item.description ? ` · ${item.description.slice(0, 56)}` : ""}</p></div></div></td><td>{item.clientName || item.opportunityTitle || "Sem vínculo"}</td><td><span className={`crm-stage ${item.priority === "high" ? "crm-stage-rose" : item.priority === "medium" ? "crm-stage-amber" : "crm-stage-slate"}`}>{PRIORITY_LABELS[item.priority]}</span></td><td className={item.dueAt && new Date(item.dueAt) < new Date() && item.status === "pending" ? "font-semibold text-rose-500" : ""}>{formatDateTime(item.dueAt)}</td><td><div className="flex justify-end gap-2">{item.status === "pending" && <button onClick={() => changeStatus(item.id, "completed")} className="crm-button-secondary px-2.5 py-1.5 text-[11px]"><Check className="h-3.5 w-3.5" /> Concluir</button>}{item.status === "completed" && <span className="flex items-center gap-1 text-xs font-semibold text-emerald-600"><Check className="h-3.5 w-3.5" /> Concluída</span>}<button onClick={() => inactivateRecord(item.id, item.title)} className="crm-icon-button text-rose-500 hover:bg-rose-50" title="Inativar atividade"><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div></section>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="crm-dialog sm:max-w-[600px]"><DialogHeader><p className="eyebrow">PLANEJAMENTO</p><DialogTitle className="font-display text-2xl text-[#172033]">Nova atividade</DialogTitle><DialogDescription>Associe a atividade ao contexto comercial sempre que houver um cliente ou oportunidade envolvidos.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-3 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="crm-field"><span>Tipo</span><select value={form.type} onChange={event => setForm(current => ({ ...current, type: event.target.value as typeof form.type }))}><option value="task">Tarefa</option><option value="appointment">Compromisso</option></select></label><label className="crm-field"><span>Prioridade</span><select value={form.priority} onChange={event => setForm(current => ({ ...current, priority: event.target.value as typeof form.priority }))}><option value="low">Baixa</option><option value="medium">Média</option><option value="high">Alta</option></select></label></div><label className="crm-field"><span>Título</span><input required minLength={2} value={form.title} onChange={event => setForm(current => ({ ...current, title: event.target.value }))} placeholder="Ex.: Preparar proposta comercial" /></label><label className="crm-field"><span>Detalhes</span><textarea rows={3} value={form.description} onChange={event => setForm(current => ({ ...current, description: event.target.value }))} placeholder="Contexto ou orientações para a atividade" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="crm-field"><span>Cliente</span><select value={form.clientId} onChange={event => setForm(current => ({ ...current, clientId: event.target.value }))}><option value="">Sem vínculo</option>{(clients.data ?? []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="crm-field"><span>Oportunidade</span><select value={form.opportunityId} onChange={event => setForm(current => ({ ...current, opportunityId: event.target.value }))}><option value="">Sem vínculo</option>{(opportunities.data?.items ?? []).map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="crm-field sm:col-span-2"><span>Prazo</span><input type="datetime-local" value={form.dueAt} onChange={event => setForm(current => ({ ...current, dueAt: event.target.value }))} /></label></div><div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={() => setDialogOpen(false)} className="crm-button-secondary">Cancelar</button><button disabled={create.isPending} className="crm-button-primary">{create.isPending ? "Criando..." : "Criar atividade"}</button></div></form></DialogContent></Dialog>
  </div>;
}
