import QueryError from "@/components/QueryError";
import { formatDateTime, INTERACTION_LABELS } from "@/lib/crm";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Mail, MessageCircle, MessageSquare, PhoneCall, Plus, StickyNote, Trash2 } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const interactionIcon = { call: PhoneCall, meeting: CalendarDays, email: Mail, message: MessageCircle, note: StickyNote };

export default function Interactions() {
  const utils = trpc.useUtils();
  const [dialogOpen, setDialogOpen] = useState(false);
  const [form, setForm] = useState({ type: "note" as "call" | "meeting" | "email" | "message" | "note", description: "", clientId: "", opportunityId: "" });
  const interactions = trpc.interactions.list.useQuery({});
  const clients = trpc.clients.options.useQuery();
  const opportunities = trpc.opportunities.list.useQuery({ page: 1, pageSize: 100 });
  const create = trpc.interactions.create.useMutation();
  const inactivate = trpc.interactions.inactivate.useMutation();
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); create.mutate({ ...form, clientId: form.clientId ? Number(form.clientId) : null, opportunityId: form.opportunityId ? Number(form.opportunityId) : null }, { onSuccess: () => { toast.success("Interação registrada na linha do tempo."); setForm({ type: "note", description: "", clientId: "", opportunityId: "" }); setDialogOpen(false); void utils.interactions.list.invalidate(); }, onError: error => toast.error(error.message) }); }
  function inactivateRecord(id: number) { if (!window.confirm("Inativar esta interação? O histórico continuará preservado.")) return; inactivate.mutate({ id }, { onSuccess: () => { toast.success("Interação inativada com histórico preservado."); void utils.interactions.list.invalidate(); }, onError: error => toast.error(error.message) }); }
  if (interactions.isError) return <QueryError message="Não foi possível carregar a linha do tempo comercial." onRetry={() => void interactions.refetch()} />;
  return <div className="space-y-7"><section className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="eyebrow">RELACIONAMENTO</p><h1 className="mt-2 font-display text-3xl font-semibold tracking-tight text-[#172033]">Linha do tempo comercial</h1><p className="mt-2 text-sm text-slate-500">Preserve cada conversa, reunião e contexto que move uma negociação.</p></div><button onClick={() => setDialogOpen(true)} className="crm-button-primary"><Plus className="h-4 w-4" /> Registrar interação</button></section>
    <section className="crm-card p-6"><div className="relative border-l border-slate-200 pl-6 sm:pl-8">{interactions.isLoading ? <p className="py-10 text-center text-sm text-slate-400">Carregando linha do tempo...</p> : (interactions.data ?? []).length === 0 ? <div className="py-12 text-center"><MessageSquare className="mx-auto h-7 w-7 text-slate-300" /><p className="mt-3 text-sm font-medium text-slate-500">O histórico comercial começa aqui</p><p className="mt-1 text-xs text-slate-400">Registre a primeira interação para manter o contexto da relação.</p></div> : interactions.data?.map(item => { const Icon = interactionIcon[item.type]; return <article key={item.id} className="relative pb-7 last:pb-0"><span className="absolute -left-[2.12rem] top-0 flex h-8 w-8 items-center justify-center rounded-xl border border-slate-200 bg-white text-[#4c58a8] sm:-left-[2.62rem]"><Icon className="h-3.5 w-3.5" /></span><div className="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm font-semibold text-slate-700">{INTERACTION_LABELS[item.type]}</p><p className="mt-1 text-xs text-slate-400">{item.clientName ?? item.opportunityTitle ?? "Registro comercial"} · por {item.authorName || "Usuário"}</p></div><div className="flex items-center gap-1"><time className="shrink-0 text-[11px] font-medium text-slate-400">{formatDateTime(item.occurredAt)}</time><button onClick={() => inactivateRecord(item.id)} className="crm-icon-button text-rose-500 hover:bg-rose-50" title="Inativar interação"><Trash2 className="h-3.5 w-3.5" /></button></div></div><p className="mt-3 max-w-3xl whitespace-pre-wrap text-sm leading-6 text-slate-600">{item.description}</p></article>; })}</div></section>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="crm-dialog sm:max-w-[600px]"><DialogHeader><p className="eyebrow">HISTÓRICO</p><DialogTitle className="font-display text-2xl text-[#172033]">Registrar interação</DialogTitle><DialogDescription>O registro será vinculado à linha do tempo e identificará o usuário responsável.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-3 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><label className="crm-field"><span>Tipo de interação</span><select value={form.type} onChange={event => setForm(current => ({ ...current, type: event.target.value as typeof form.type }))}><option value="call">Ligação</option><option value="meeting">Reunião</option><option value="email">E-mail</option><option value="message">Mensagem</option><option value="note">Anotação</option></select></label><label className="crm-field"><span>Cliente</span><select value={form.clientId} onChange={event => setForm(current => ({ ...current, clientId: event.target.value }))}><option value="">Selecione um cliente</option>{(clients.data ?? []).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label></div><label className="crm-field"><span>Oportunidade relacionada</span><select value={form.opportunityId} onChange={event => setForm(current => ({ ...current, opportunityId: event.target.value }))}><option value="">Nenhuma oportunidade específica</option>{(opportunities.data?.items ?? []).map(item => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label><label className="crm-field"><span>Descrição</span><textarea required minLength={2} maxLength={5000} rows={6} value={form.description} onChange={event => setForm(current => ({ ...current, description: event.target.value }))} placeholder="Registre os pontos principais, próximos passos e compromissos assumidos." /></label><p className="text-xs text-slate-400">Vincule ao menos um cliente ou uma oportunidade.</p><div className="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" onClick={() => setDialogOpen(false)} className="crm-button-secondary">Cancelar</button><button disabled={create.isPending || (!form.clientId && !form.opportunityId)} className="crm-button-primary">{create.isPending ? "Registrando..." : "Registrar interação"}</button></div></form></DialogContent></Dialog>
  </div>;
}
